bsuirach/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('loginsys.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^employees/', include('employees.urls')),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^', include('home.urls')),
]

employees/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'employees'

urlpatterns = [
    url(r'^(?P<employee_id>[0-9]+)/$', views.show, name='show'),
    url(r'^update/$', views.update, name='update'),
]

home/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index),
]

loginsys/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'loginsys'

urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
]

users/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^(?P<username>\w+)/$', views.show, name='show'),
    url(r'^(?P<username>\w+)/edit$', views.edit, name='edit'),
    url(r'^(?P<username>\w+)/update$', views.update, name='update'),
]

employees/models.py
from django.db import models


class Employee(models.Model):
    academicDepartment = models.CharField(max_length=100)
    calendarId = models.CharField(max_length=250)
    firstName = models.CharField(max_length=100)
    bsuir_id = models.IntegerField()
    lastName = models.CharField(max_length=100)
    middleName = models.CharField(max_length=100)
    photoLink = models.URLField(max_length=250)
    description = models.TextField()

home/models.py
from django.db import models

# Create your models here.

loginsys/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

employees/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from .models import Employee
from .bsuirapi import get_employees


def show(request, employee_id):
    employee = get_object_or_404(Employee, pk=employee_id)
    return render(request, 'employees/show.html', {'employee': employee, 'username': request.user.username})


@user_passes_test(lambda u: u.is_superuser)
def update(request):
    employees = get_employees()
    for empl in employees:
        employee, _ = Employee.objects.get_or_create(bsuir_id=int(empl['id']))
        employee.academicDepartment = empl['academicDepartment']
        employee.calendarId = empl['calendarId']
        employee.firstName = empl['firstName']
        employee.lastName = empl['lastName']
        employee.middleName = empl['middleName']
        employee.photoLink = empl['photoLink']
        employee.description = empl['rank']
        employee.save()
    return HttpResponse("Success")

home/views.py
from django.shortcuts import render_to_response
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.template.context_processors import csrf
from django.db import models
from employees.models import Employee

def index(request):
    employees = Employee.objects.all()
    return render_to_response('home/index.html', {'employees': employees, 'username': auth.get_user(request).username})

loginsys/views.py
from django.shortcuts import render_to_response, redirect
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm
from django.template.context_processors import csrf


def login(request):
    args = {}
    args.update(csrf(request))
    if request.POST:
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            args['login_error'] = "User not found"
            return render_to_response('login.html', args)

    else:
        return render_to_response('login.html', args)


def logout(request):
    auth.logout(request)
    return redirect("/")


def register(request):
    args = {}
    args.update(csrf(request))
    args['form'] = UserCreationForm()
    if request.POST:
        newuser_form = UserCreationForm(request.POST)
        if newuser_form.is_valid():
            newuser_form.save()
            newuser = auth.authenticate(username=newuser_form.cleaned_data['username'],
                                        password=newuser_form.cleaned_data['password2'])
            auth.login(request, newuser)
            return redirect('/')
        else:
            args['form'] = newuser_form
    return render_to_response('register.html', args)

users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User


def show(request, username):
    user = get_object_or_404(User, username=username)
    return render(request, 'users/show.html', {'user': user, 'username': request.user})


def edit(request, username):
    user = request.user
    if username != user.username:
        return redirect("/")
    return render(request, 'users/edit.html', {'user': user, 'username': username})

def update(request, username):
    user = request.user
    if username != user.username:
        return
    user.username = request.POST['username']
    user.first_name = request.POST['first_name']
    user.last_name = request.POST['last_name']
    user.email = request.POST['email']
    user.save()
    return redirect('/users/' + user.username)

employees/templates/employees/show.html
{% extends 'main.html' %}
{% load static %}
{% load comments %}
{% load ratings %}

{% block body %}

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<div class="container">
  <div class="row">
    <div class="col-md-offset-2 col-md-8 col-xs-10">
      <div class="well panel panel-default">
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-12 col-sm-3 text-center">
                <img
                    {% if employee.photoLink %}
                       src="{{ employee.photoLink }}"
                    {% else %}
                       src="{% static 'default_avatar.png' %}"
                    {% endif %}
                    alt="лицо {{ employee.lastName }}" class="center-block img-circle img-thumbnail img-responsive">
            </div>
            <div class="col-xs-12 col-sm-8">
                <h2>{{ employee.lastName }}
                    {{ employee.firstName }}
                    {{ employee.middleName }}</h2>
                <h5><strong><a href='https://www.bsuir.by/schedule/scheduleEmployee.xhtml?id={{ employee.bsuir_id }}'>Расписание</a></strong></h5>
                <h5><strong>Кафедра: </strong> {{ employee.academicDepartment }} </h5>
                <h5><strong>Разведка докладывает: </strong> {{ employee.description }} </h5>

            </div>
          </div>
        </div>
      </div>
      <div class='col-xs-offset-2 col-xs-8'>
          <p>{% ratings employee %}</p>
      <p>
          {% get_comment_count for employee as comment_count %}
          <strong>{{ comment_count }} comments<strong>
      </p>
      {% get_comment_list for employee as comment_list %}
      <ul class="media-list">
          {% for comment in comment_list %}
          <li class="media">
              <a href="#" class="pull-left">
                  <img src="{% static 'default_avatar.png' %}" alt="" class="img-circle" height="65" width="65">
              </a>
              <div class="media-body">
                  <span class="text-muted pull-right">
                      <small class="text-muted">{{ comment.submit_date }}</small>
                  </span>
                  <strong class="text-success">{{ comment.user_name }}</strong>
                  <p>
                      {{ comment.comment }}
                  </p>
              </div>
          </li>
          {% endfor %}
      </ul>

          {% if user.is_authenticated %}
             {% get_comment_form for employee as form %}
          <form action="{% comment_form_target %}" method="POST">
             {% csrf_token %}
              <textarea class="form-control" id="id_comment" maxlength="3000" name="comment" required></textarea>
              <input type="hidden" id="id_honeypot" name="honeypot" type="text" />
             {{ form.content_type }}
             {{ form.object_pk }}
             {{ form.timestamp }}
             {{ form.security_hash }}
              <input type="hidden" name="next" value="{% url 'employees:show' employee.id %}" />
              <input type="submit" class='btn btn-default' value="Add comment" id="id_submit" />
          </form>
          {% else %}
          <p>Please <a href="{% url 'loginsys:login' %}">log in</a> to leave a comment.</p>
          {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

employees/templates/star_ratings/widget.html
{% extends "star_ratings/widget_base.html" %}
{% block rating_detail %}

({{ rating.average|floatformat:"-2" }} баллаў)

<p><strong>{{ rating.count }} людей проголосовало

    {% if user_rating %}
        (ты поставил {{ user_rating.score }})
    {% else %}
        (ты не ставил)
    {% endif %}
    {% if not user.is_authenticated and not anonymous_ratings and not read_only %}
</strong>
        <p>Залогинься, чтоб проголосовать</p>
    {% endif %}

</p>
    <div class="star-ratings-errors"></div>
{% endblock %}

home/templates/home/index.html
{% extends 'main.html' %}

{% block body %}
<div class='jumbotron'>
        <h1>BSUIRach - your new family</h1>
        <br />
        <h3>Teachers:</h3>
        <ul>
            {% for employee in employees %}
            <li>
                <a href='/employees/{{ employee.id }}'>
                {{ employee.lastName }}
                {{ employee.firstName }}
                {{ employee.middleName }}
                (каф. {{ employee.academicDepartment }})
                </a>
            </li>
            {% endfor %}
        </ul>
</div>
{% endblock %}

loginsys/templates/login.html
{% extends 'main.html' %}

{% block body %}

<div class="container">
  <div class="col-xs-offset-4 col-xs-4">
    <div class="well" align="center">
      <fieldset>
        <legend>Login</legend>
        <form method="post" action="/auth/login/">
             {% csrf_token %}
             {% if login_error %}
            <div class="alert alert-danger">{{ login_error }}</div>
        {% endif %}
            <div class="form-group">
                <input type="text" name="username" id="username" class="form-control" placeholder="Username">
            </div>

            <div class="form-group">
                <input type="password" name="password" id="password" class='form-control' placeholder="Password">
            </div>
            <div class="actions">
                <input class="btn btn-default" type="submit" value="OK">
                <br />
                <div class="label round secondary"><a href="/auth/register/">Registration</a></div>

            </div>
        <br/>
      </fieldset>
    </div>
  </div>
</div>

{% endblock %}

loginsys/templates/register.html
{% extends 'main.html' %}

{% block body %}

{{ form }}
<!-- <div class="container">
     <div class="col-xs-offset-4 col-xs-4">
     <div class="well" align="center">
     <fieldset>
     <legend>Registration</legend>
     <form method="post" action="/auth/register/">
     {% csrf_token %}
     <div class="form-group">
     <input id="username" class="form-control" placeholder="Username" maxlength="150" name="username" type="text" required>
     </div>

     <div class="form-group">
     <input  class='form-control' placeholder="Password" id="id_password1" name="password1" type="password" required>
     </div>

     <div class="form-group">
     <input  class='form-control' placeholder="Password confirmation" id="id_password2" name="password2" type="password" required>
     </div>

     <div class="alert alert-info">Password equired. 150 characters or fewer. Letters, digits and @/./+/-/_ only.</div>

     <div class="actions">
     <input class="btn btn-default" type="submit" value="OK">
     </div>
     <br/>
     </fieldset>
     </div>
     </div>
     </form> -->
{% endblock %}

templates/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>BSUIRach</title>
        <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" type="text/css" media="screen" />
        <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}" type="text/css" media="screen" />
        <link rel="stylesheet" href="{% static 'common.css' %}" type="text/css" media="screen" />
        <script src="{% static 'jquery.min.js' %}"></script>
        <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    </head>
    <body>


        <nav class="navbar navbar-default navbar-fixed-top"">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">BSUIRach</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <!-- <li><a href="#">Link</a></li> -->
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                       {% if username %}
                        <li><a href="/users/{{ username }}">{{ username }}</a></li>
                        <li class="divider"></li>
                        <li><a href="/auth/logout/">Logout</a></li>
                       {% else %}
                        <li><a href="/auth/login/">Login</a></li>
                        <li><a href="/auth/register/">Sign up</a></li>
                       {% endif %}

                    </ul>
                    </ul>
                </div>
            </div>
        </nav>

        <div id="wrap">
            <div class="container">
            {% block body %}{% endblock %}
            </div>
            <div id="push"></div>
        </div>

        <div class="container">
            <p class="muted credit" style='text-align:center'>
                <a href="http://github.com/alex-pat/bsuirach">
                    6TPO (The Specks), 2017. Fork Us on github
                </a>
            </p>
        </div>

    </body>
</html>

users/templates/users/edit.html
{% extends 'main.html' %}
{% load static %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="panel panel-white profile-widget">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="image-container bg2" style='background-image:url("{% static 'wallpaper.jpeg' %}")'>
                            <img src="{% static 'default_avatar.png' %}" class="avatar" alt="avatar">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="details">
                            <h4>{{ user.first_name }} {{ user.last_name }}<i class="fa fa-sheild"></i></h4>
                            <div>{{ user.username }}</div>
                            <div>{{ user.email }}</div>
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">

                <div class="col-sm-6 col-sm-offset-3">
                    <form method="POST" action="/users/{{ username }}/update">
                        {% csrf_token %}
                        <div class="panel panel-white border-top-purple">
                            <div class="panel-heading">
                                <h3 class="panel-title">Edit info</h3>
                                <div class="controls pull-right">
                                    <span class="pull-right clickable">
                                        <i class="fa fa-chevron-up"></i>
                                    </span>
                                </div>
                            </div>
                            <div class="panel-body">
                                <div class="body-section">
                                    <h5 class="section-heading">Username</h5>
                                    <p class="section-content">
                                        <input type="text" name="username" value="{{ user.username }}" class='form-control'/>
                                    </p>
                                </div>
                                <div class="body-section">
                                    <h5 class="section-heading">First name</h5>
                                    <p class="section-content">
                                        <input type="text" name="first_name" value="{{ user.first_name }}" class='form-control'/>
                                    </p>
                                </div>
                                <div class="body-section">
                                    <h5 class="section-heading">Last name</h5>
                                    <p class="section-content">
                                        <input type="text" name="last_name" value="{{ user.last_name }}" class='form-control'/>
                                    </p>
                                </div>
                                <div class="body-section">
                                    <h5 class="section-heading">Email</h5>
                                    <p class="section-content">
                                        <input type="text" name="email" value="{{ user.email }}" class='form-control'/>
                                    </p>
                                </div>
                                <input type="submit" class='btn btn-primary'>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/show.html
{% extends 'main.html' %}
{% load static %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="panel panel-white profile-widget">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="image-container bg2" style='background-image:url("{% static 'wallpaper.jpeg' %}")'>
                            <img src="{% static 'default_avatar.png' %}" class="avatar" alt="avatar">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="details">
                            <h4>{{ user.first_name }} {{ user.last_name }}<i class="fa fa-sheild"></i></h4>
                            <div>{{ user.username }}</div>
                            <div>{{ user.email }}</div>
                        </div>
                    </div>

                </div>
            </div>

            <div class="row">

                <div class="col-sm-6">

                    <div class="panel panel-white border-top-purple">
                        <div class="panel-heading">
                            <h3 class="panel-title">My Story</h3>
                            <div class="controls pull-right">
                                <span class="pull-right clickable">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="body-section">
                                <h5 class="section-heading">About</h5>
                                <p class="section-content">A brief description of you</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Introduction</h5>
                                <p class="section-content">Put a little about yourself here so people know they've found the correct Kevin.</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Acheivements</h5>
                                <p class="section-content">Examples: survived high school, have 3 kids, etc.</p>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-white border-top-light-blue">
                        <div class="panel-heading">
                            <h3 class="panel-title">My Schedule</h3>
                            <div class="controls pull-right">
                                <span class="pull-right clickable">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="body-section">
                                <h5 class="section-heading">Current Plan: Basic Plan</h5>
                                <ul>
                                    <li>ЛР: 512-5 ТРиТПО (Яночкин)</li>
                                    <li>ЛР: 501-5 ЦОСиИ (Третьяков)</li>
                                    <li>ЛР: 512-5 ТРиТПО (Яночкин)</li>
                                    <li>ЛР: 207-5 АКСиС (Калинин)</li>
                                    <li>ЛР: 502-5 СА (Иванов)</li>
                                </ul>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-white border-top-pink">
                        <div class="panel-heading">
                            <h3 class="panel-title">My Tasks</h3>
                            <div class="controls pull-right">
                                <span class="pull-right clickable">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="body-section">
                                <h5 class="mg-top-0">Completed Pre-Orders - 90%</h5>
                                <div class="progress progress-xs">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
                                </div>
                            </div>
                            <div class="body-section">
                                <h5>Completed Orders - 40%</h5>
                                <div class="progress progress-xs">
                                    <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

                <div class="col-sm-6">

                    <div class="panel panel-white border-top-green">
                        <div class="panel-heading">
                            <h3 class="panel-title">User Info</h3>
                            <div class="controls pull-right">
                                <span class="pull-right clickable">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                            </div>
                        </div>

                        <div class="panel-body">
                            <div class="body-section">
                                <h5 class="section-heading">Username</h5>
                                <p class="section-content"> {{ user.username }}</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">First name</h5>
                                <p class="section-content">{{ user.first_name }}</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Last name</h5>
                                <p class="section-content">{{ user.last_name }}</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Email</h5>
                                <p class="section-content">{{ user.email }}</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Date joined</h5>
                                <p class="section-content">{{ user.date_joined.isoformat }}</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Last login</h5>
                                <p class="section-content">{{ user.last_login.isoformat }}</p>
                            </div>
                            <div class="body-section">
                                <a href='/users/{{ user.username }}/edit' class='btn btn-default'>Edit</a>
                            </div>
                        </div>
                    </div>

                    <div class="panel panel-white border-top-orange">
                        <div class="panel-heading">
                            <h3 class="panel-title">Social Statistics</h3>
                            <div class="controls pull-right">
                                <span class="pull-right clickable">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="body-section">
                                <h5 class="section-heading">Friends</h5>
                                <p class="section-content">242</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Posts</h5>
                                <p class="section-content">2240</p>
                            </div>
                            <div class="body-section">
                                <h5 class="section-heading">Pictures</h5>
                                <p class="section-content">18</p>
                            </div>
                        </div>
                    </div>

                  {% if user.is_superuser %}
                    <div class="panel panel-white border-top-black">
                        <div class="panel-heading">
                            <h3 class="panel-title">Admin tools</h3>
                            <div class="controls pull-right">
                                <span class="pull-right clickable">
                                    <i class="fa fa-chevron-up"></i>
                                </span>
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="body-section">
                                <a id="employee-updater" class="btn btn-success has-spinner">
                                    <span class="text">
                                        Update employees
                                    </span>
                                    <span class="spinner">
                                        <i class="fa fa-refresh fa-spin fa-fw"></i>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                  {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
 $("#employee-updater").on('click', function(event) {
     $.get({
         url: "{% url 'employees:update' %}",
         beforeSend: function() {
             $("#employee-updater .text").text("Update employees");
             $("#employee-updater").toggleClass('active');
             $("#employee-updater").toggleClass('disabled');
         },
         success: function(response) {
             $("#employee-updater").toggleClass('active');
             $("#employee-updater").toggleClass('disabled');
             $("#employee-updater .text").append('&nbsp;<i class="fa fa-check" aria-hidden="true"></i>');
         }
     });
 });
</script>

{% endblock %}